spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_boot
    driver-class-name: org.postgresql.Driver
    username: srthk
    password: hellofatty
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format-sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
